import { TableColumn } from "@/types";

export const tableColumns: TableColumn[] = [
  {
    key: "name",
    label: "Company",
    sortable: true,
    format: "text",
    width: "200px",
    align: "left",
  },
  {
    key: "price",
    label: "Price",
    sortable: true,
    format: "currency",
    width: "120px",
    align: "right",
  },
  {
    key: "priceChange3Mo",
    label: "% Price Δ 3-Mo",
    sortable: true,
    format: "percentage",
    width: "140px",
    align: "right",
  },
  {
    key: "priceChange12Mo",
    label: "% Price Δ 12-Mo",
    sortable: true,
    format: "percentage",
    width: "140px",
    align: "right",
  },
  {
    key: "marketCap",
    label: "Market Cap.",
    sortable: true,
    format: "currency",
    width: "140px",
    align: "right",
  },
  {
    key: "enterpriseValue",
    label: "Enterprise Value (EV)",
    sortable: true,
    format: "currency",
    width: "180px",
    align: "right",
  },
  {
    key: "evToImpliedArr",
    label: "EV / Implied ARR",
    sortable: true,
    format: "ratio",
    width: "160px",
    align: "right",
  },
  {
    key: "evToNtmRevenue",
    label: "EV / NTM Rev.",
    sortable: true,
    format: "ratio",
    width: "140px",
    align: "right",
  },
  {
    key: "evToNtmGrossProfit",
    label: "EV / NTM Gross Profit",
    sortable: true,
    format: "ratio",
    width: "180px",
    align: "right",
  },
  {
    key: "evToNtmFcf",
    label: "EV / NTM FCF",
    sortable: true,
    format: "ratio",
    width: "140px",
    align: "right",
  },
  {
    key: "growthAdjEvToNtmRev",
    label: "Growth Adj. EV / NTM Rev.",
    sortable: true,
    format: "ratio",
    width: "200px",
    align: "right",
  },
  {
    key: "ntmFcf",
    label: "NTM FCF",
    sortable: true,
    format: "currency",
    width: "120px",
    align: "right",
  },
  {
    key: "impliedArr",
    label: "Implied ARR",
    sortable: true,
    format: "currency",
    width: "140px",
    align: "right",
  },
  {
    key: "netNewArr",
    label: "Net New ARR",
    sortable: true,
    format: "currency",
    width: "140px",
    align: "right",
  },
  {
    key: "ltmRevenue",
    label: "LTM Rev.",
    sortable: true,
    format: "currency",
    width: "120px",
    align: "right",
  },
  // % YoY Growth Section
  {
    key: "ltmRevenueGrowth",
    label: "LTM Rev. Growth",
    sortable: true,
    format: "percentage",
    width: "140px",
    align: "right",
  },
  {
    key: "ntmRevenueGrowth",
    label: "NTM Rev. Growth",
    sortable: true,
    format: "percentage",
    width: "140px",
    align: "right",
  },
  // % LTM Margins Section
  {
    key: "grossMargin",
    label: "GM",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "salesAndMarketingMargin",
    label: "S&M",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "researchAndDevelopmentMargin",
    label: "R&D",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "generalAndAdminMargin",
    label: "G&A",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "operatingExpensesMargin",
    label: "OpEx",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "operatingIncomeMargin",
    label: "OpIn",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  {
    key: "freeCashFlowMargin",
    label: "FCF",
    sortable: true,
    format: "percentage",
    width: "100px",
    align: "right",
  },
  // Advanced Operating Metrics
  {
    key: "ntmFcfMargin",
    label: "NTM % FCF Margin",
    sortable: true,
    format: "percentage",
    width: "160px",
    align: "right",
  },
  {
    key: "ruleOf40",
    label: "NTM Rule of 40",
    sortable: true,
    format: "percentage",
    width: "140px",
    align: "right",
  },
  {
    key: "magicNumber",
    label: "Magic Number",
    sortable: true,
    format: "ratio",
    width: "140px",
    align: "right",
  },
  {
    key: "paybackPeriod",
    label: "Payback Period",
    sortable: true,
    format: "number",
    width: "140px",
    align: "right",
  },
  {
    key: "impliedAverageAcv",
    label: "Implied Average ACV",
    sortable: true,
    format: "currency",
    width: "160px",
    align: "right",
  },
  {
    key: "customerCount",
    label: "Customer Count",
    sortable: true,
    format: "number",
    width: "140px",
    align: "right",
  },
  {
    key: "impliedArrPerFte",
    label: "Implied ARR / FTE",
    sortable: true,
    format: "currency",
    width: "160px",
    align: "right",
  },
  {
    key: "annualizedOpexPerFte",
    label: "Annualized OpEx / FTE",
    sortable: true,
    format: "currency",
    width: "180px",
    align: "right",
  },
  {
    key: "netDollarRetention",
    label: "Net Dollar Retention",
    sortable: true,
    format: "percentage",
    width: "160px",
    align: "right",
  },
  {
    key: "multipleReturnSinceIpo",
    label: "Multiple Return Since IPO",
    sortable: true,
    format: "ratio",
    width: "180px",
    align: "right",
  },
];

// Default visible columns - Show all columns
export const defaultVisibleColumns = [
  "name",
  "price",
  "priceChange3Mo",
  "priceChange12Mo",
  "marketCap",
  "enterpriseValue",
  "evToImpliedArr",
  "evToNtmRevenue",
  "evToNtmGrossProfit",
  "evToNtmFcf",
  "growthAdjEvToNtmRev",
  "ntmFcf",
  "impliedArr",
  "netNewArr",
  "ltmRevenue",
  "ltmRevenueGrowth",
  "ntmRevenueGrowth",
  "grossMargin",
  "salesAndMarketingMargin",
  "researchAndDevelopmentMargin",
  "generalAndAdminMargin",
  "operatingExpensesMargin",
  "operatingIncomeMargin",
  "freeCashFlowMargin",
  "ntmFcfMargin",
  "ruleOf40",
  "magicNumber",
  "paybackPeriod",
  "impliedAverageAcv",
  "customerCount",
  "impliedArrPerFte",
  "annualizedOpexPerFte",
  "netDollarRetention",
  "multipleReturnSinceIpo",
];
